name: mahabharata_wisdom
description: Daily wisdom from Mahabharata
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_tts: ^4.0.2
  share_plus: ^7.2.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.4 

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/logo.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"